name = "prompt-gallery"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages 配置
pages_build_output_dir = "dist"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "prompt-gallery-db"
database_id = "da6c0397-8e9c-432f-a512-ab54c8f6a5ca"

# 环境变量
[vars]
ENVIRONMENT = "production"

# R2 存储绑定（可选，用于大文件存储）
# [[r2_buckets]]
# binding = "ASSETS"
# bucket_name = "prompt-gallery-assets"
